
ALTER TABLE planning_application
ADD COLUMN LGAIDs 
    WHEN lga_fullname = "bayside_vic" THEN 'LGA20910'
     WHEN lga_fullname = "melbourne_city" THEN 'LGA24600'
   WHEN lga_fullname = "city_of_port_phillip"  THEN 'LGA25900'
     WHEN lga_fullname = "greater_dandenong" THEN 'LGA22670'
     WHEN lga_fullname = "kingston" THEN 'LGA23430'
     WHEN lga_fullname = "boroondara_city" THEN 'LGA21110'
     WHEN lga_fullname = "casey" THEN 'LGA21610'
     WHEN lga_fullname = "frankston_city" THEN 'LGA22170'
     WHEN lga_fullname = "stonnington" THEN 'LGA26350'
     WHEN lga_fullname = "darebin" THEN 'LGA21890'
     WHEN lga_fullname = "hume" THEN 'LGA23270'
     WHEN lga_fullname = "hobsons_bay" THEN 'LGA23110'
     WHEN lga_fullname = "knox" THEN 'LGA23670'
     WHEN lga_fullname = "manningham" THEN 'LGA24210'
     WHEN lga_fullname = "banyule" THEN 'LGA20660'
     WHEN lga_fullname = "cardinia" THEN 'LGA21450'
     WHEN lga_fullname = "brimbank" THEN 'LGA21180'
     WHEN lga_fullname = "maribyrnong" THEN 'LGA24330'
     WHEN lga_fullname = "maroondah_city" THEN 'LGA24410'
     WHEN lga_fullname = "moreland_city" THEN 'LGA25250' 
     WHEN lga_fullname = "melton" THEN 'LGA24650'
     WHEN lga_fullname = "monash" THEN 'LGA24970'
     WHEN lga_fullname = "moonee_valley" THEN 'LGA25060'
     WHEN lga_fullname = "mornington_peninsula" THEN 'LGA25340'
     WHEN lga_fullname = "whitehorse" THEN 'LGA26980'
     WHEN lga_fullname = "wyndham" THEN 'LGA27260'
     WHEN lga_fullname = "yarra_city" THEN 'LGA27350'
     WHEN lga_fullname = "yarra_ranges" THEN 'LGA27450'
     WHEN lga_fullname = "glen_eira" THEN 'LGA22310'
     WHEN lga_fullname = "nillumbik" THEN 'LGA25710'
     WHEN lga_fullname = "latrobe" THEN 'LGA23810'
     ELSE lga_fullname = "lga_fullname"
    ;
